apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa 
spec:
  scaleRef:
    kind: DeploymentConfig 
    name: gotest
    apiVersion: v1 
    subresource: scale
  minReplicas: 1 
  maxReplicas: 10 
  cpuUtilization:
    targetPercentage: 40
